# Generated by Django 4.1.4 on 2022-12-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
